(()=>{
const MARK='xvdProcessed',cache=new Map(),MAX_CACHE=400;let enabled=true,preferBest=false,showCopy=true,warnDuplicate=true;let history=[];const downloads=new Map();
chrome.storage.local.get({enabled:true,preferBest:false,showCopy:true,warnDuplicate:true,downloadHistory:[]},r=>{enabled=r.enabled;preferBest=r.preferBest;showCopy=r.showCopy;warnDuplicate=r.warnDuplicate;history=r.downloadHistory||[];scan()});
chrome.storage.onChanged.addListener(c=>{if(c.enabled){enabled=c.enabled.newValue;reset();scan()}if(c.preferBest)preferBest=c.preferBest.newValue;if(c.showCopy)showCopy=c.showCopy.newValue;if(c.warnDuplicate)warnDuplicate=c.warnDuplicate.newValue;if(c.downloadHistory)history=c.downloadHistory.newValue||[]});
window.addEventListener('message',e=>{if(e.source!==window||e.data?.source!=='xvd-page-hook-v7'||e.data?.type!=='media')return;const id=String(e.data.id||'');if(!id)return;cache.delete(id);cache.set(id,e.data.videos||[]);while(cache.size>MAX_CACHE)cache.delete(cache.keys().next().value)});
function reset(){document.querySelectorAll('.xvd-wrap').forEach(n=>n.remove());document.querySelectorAll('article').forEach(a=>delete a.dataset[MARK])}
function normalize(items){const out=new Map();for(const x of items||[]){const url=typeof x==='string'?x:x.url;if(!/^https:\/\/video\.twimg\.com\//.test(url||''))continue;let w=Number(x.w)||0,h=Number(x.h)||0;const m=url.match(/\/(\d+)x(\d+)\//);if(m){w=+m[1];h=+m[2]}const bitrate=Number(x.bitrate)||0,label=h?`${h}p`:bitrate?`${Math.round(bitrate/1000)} kbps`:'MP4';const key=`${w}x${h}:${bitrate||label}`;if(!out.has(key))out.set(key,{url,w,h,bitrate,label})}return [...out.values()].sort((a,b)=>(b.h-a.h)||(b.w-a.w)||(b.bitrate-a.bitrate))}
function statusLinks(a){return [...a.querySelectorAll('a[href*="/status/"]')].map(x=>x.getAttribute('href')).filter(h=>/\/[^/]+\/status\/\d+/.test(h||''))}
function ownStatusLink(a){const time=a.querySelector('time');const fromTime=time?.closest('a[href*="/status/"]')?.getAttribute('href');if(fromTime&&/\/[^/]+\/status\/\d+/.test(fromTime))return fromTime;return statusLinks(a)[0]||''}
function meta(a){const m=ownStatusLink(a).match(/\/([^/]+)\/status\/(\d+)/);return{user:m?.[1]||'x',id:m?.[2]||''}}
function direct(a){const raw=[];a.querySelectorAll('video').forEach(v=>[v.currentSrc,v.src,...[...v.querySelectorAll('source')].map(s=>s.src)].filter(Boolean).forEach(url=>raw.push({url})));return [{index:0,type:'video',variants:normalize(raw)}]}
function videos(a){const {id}=meta(a),xs=(id&&cache.get(id))||direct(a);return xs.map((x,i)=>({...x,index:x.index??i,variants:normalize(x.variants)})).filter(x=>x.variants.length)}
function closeMenus(){document.querySelectorAll('.xvd-menu').forEach(n=>n.remove())}function safe(s){return String(s).replace(/[^a-zA-Z0-9._-]+/g,'_').slice(0,80)}
function filename(a,v,idx,type){const m=meta(a);return`x_${type==='animated_gif'?'gif':'video'}_${safe(m.user)}_${m.id||Date.now()}${idx?`_${idx+1}`:''}_${safe(v.label)}.mp4`}
function toast(text){let n=document.querySelector('.xvd-toast');if(!n){n=document.createElement('div');n.className='xvd-toast';document.documentElement.append(n)}n.textContent=text;n.classList.add('show');clearTimeout(n._t);n._t=setTimeout(()=>n.classList.remove('show'),1800)}
async function askDuplicate(){return new Promise(resolve=>{document.querySelector('.xvd-confirm')?.remove();const n=document.createElement('div');n.className='xvd-confirm';n.innerHTML='<div class="xvd-confirm-card"><b>再次下载？</b><span>这个视频的相同清晰度已经存在于下载历史中。</span><div><button data-no>取消</button><button data-yes>继续下载</button></div></div>';document.documentElement.append(n);const done=v=>{n.remove();resolve(v)};n.querySelector('[data-no]').onclick=()=>done(false);n.querySelector('[data-yes]').onclick=()=>done(true);n.onclick=e=>{if(e.target===n)done(false)}})}
async function download(a,v,idx,b,type){if(warnDuplicate&&history.some(x=>x.url===v.url)&&!(await askDuplicate()))return;b.disabled=true;const sm=b.querySelector('small');if(sm)sm.textContent='正在开始…';chrome.runtime.sendMessage({type:'XVD_DOWNLOAD',url:v.url,filename:filename(a,v,idx,type)},r=>{if(chrome.runtime.lastError||!r?.ok){b.disabled=false;if(sm)sm.textContent='失败';toast('下载失败')}else{downloads.set(r.id,{button:b,label:v.label});if(sm)sm.textContent='0%';toast(`正在下载 ${v.label}`)}})}
chrome.runtime.onMessage.addListener(m=>{if(m?.type!=='XVD_PROGRESS')return;const d=downloads.get(m.id);if(!d)return;const sm=d.button?.querySelector('small');if(m.state==='complete'){if(sm)sm.textContent='完成';d.button.disabled=false;downloads.delete(m.id);toast('下载完成');setTimeout(closeMenus,500)}else if(m.state==='interrupted'){if(sm)sm.textContent='失败';d.button.disabled=false;downloads.delete(m.id);toast('下载已中断')}else if(Number.isFinite(m.percent)&&sm)sm.textContent=`${m.percent}%`});
function copyUrl(v){navigator.clipboard.writeText(v.url).then(()=>toast('视频链接已复制')).catch(()=>toast('复制视频链接失败'))}
function qualityButton(menu,a,v,idx,type,isBest){const row=document.createElement('div');row.className='xvd-quality-row';const b=document.createElement('button');b.className='xvd-quality';b.innerHTML=`<span>${v.label}${isBest?' <em>最高</em>':''}</span><small>${v.w?`${v.w}×${v.h}`:'MP4'}</small>`;b.onclick=e=>{e.stopPropagation();download(a,v,idx,b,type)};const copy=document.createElement('button');copy.className='xvd-copy';copy.title='复制视频链接';copy.textContent='⧉';copy.onclick=e=>{e.stopPropagation();copyUrl(v)};row.append(b);if(showCopy)row.append(copy);menu.append(row)}
function downloadAll(a,vs,b){b.disabled=true;let delay=0;vs.forEach((vid,idx)=>{const v=vid.variants[0];setTimeout(()=>chrome.runtime.sendMessage({type:'XVD_DOWNLOAD',url:v.url,filename:filename(a,v,idx,vid.type)},r=>{if(r?.ok)downloads.set(r.id,{button:b,label:v.label})}),delay);delay+=220});toast(`正在开始下载 ${vs.length} 个视频`);setTimeout(()=>{b.disabled=false;closeMenus()},Math.max(1000,delay+250))}
function buildMenu(a,wrap){const menu=document.createElement('div');menu.className='xvd-menu';const vs=videos(a);if(!vs.length){menu.innerHTML='<div class="xvd-title">下载视频</div><div class="xvd-note">正在获取视频清晰度，请保持该帖子可见片刻；如果仍未获取到，可播放一次视频后重试。</div>';return menu}if(preferBest&&vs.length===1){download(a,vs[0].variants[0],0,wrap.querySelector('.xvd-btn'),vs[0].type);return null}const head=document.createElement('div');head.className='xvd-head';head.innerHTML=`<div class="xvd-title">${vs.length>1?`${vs.length} 个视频`:'下载视频'}</div>`;if(vs.length>1){const all=document.createElement('button');all.className='xvd-all';all.textContent='全部下载 · 最高画质';all.onclick=e=>{e.stopPropagation();downloadAll(a,vs,all)};head.append(all)}menu.append(head);vs.forEach((vid,idx)=>{if(vs.length>1){const h=document.createElement('div');h.className='xvd-section';h.textContent=`视频 ${idx+1}${vid.type==='animated_gif'?' · GIF':''}`;menu.append(h)}vid.variants.forEach((v,j)=>qualityButton(menu,a,v,idx,vid.type,j===0))});return menu}
function findActionBar(a){const groups=[...a.querySelectorAll('[role="group"]')];return groups.find(g=>g.querySelector('[data-testid="reply"], [data-testid="retweet"], [data-testid="like"]'))||groups.find(g=>g.querySelector('button[aria-label*="回复"],button[aria-label*="Reply"],button[aria-label*="喜欢"],button[aria-label*="Like"]'))||null}
function hasVideo(a){return !!a.querySelector('video,[data-testid="videoPlayer"],[data-testid="videoComponent"]')}
function add(a){if(!enabled||a.dataset[MARK]||!hasVideo(a))return;const bar=findActionBar(a);if(!bar)return;a.dataset[MARK]='1';const wrap=document.createElement('span');wrap.className='xvd-wrap';const btn=document.createElement('button');btn.className='xvd-btn';btn.type='button';btn.title='下载视频';btn.setAttribute('aria-label','下载视频');btn.innerHTML='<span class="xvd-icon" aria-hidden="true">↓</span><span class="xvd-label">下载</span>';wrap.append(btn);bar.append(wrap);btn.onclick=e=>{e.preventDefault();e.stopPropagation();const was=wrap.querySelector('.xvd-menu');closeMenus();if(was)return;const menu=buildMenu(a,wrap);if(menu)wrap.append(menu)}}
function scan(root=document){root.querySelectorAll?.('article').forEach(add)}let timer;new MutationObserver(ms=>{if(!enabled)return;clearTimeout(timer);timer=setTimeout(()=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1){const article=n.matches?.('article')?n:n.closest?.('article');if(article)add(article);scan(n)}},100)}).observe(document.documentElement,{childList:true,subtree:true});
let lastUrl=location.href;setInterval(()=>{if(location.href!==lastUrl){lastUrl=location.href;closeMenus();setTimeout(()=>scan(),250)}},500);
document.addEventListener('click',e=>{if(!e.target.closest('.xvd-wrap'))closeMenus()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenus()});
})();